ARG BUILDENV_TAG

FROM gcr.io/eoscanada-shared-services/nodeos-buildenv:$BUILDENV_TAG as builder

ARG SRCTAG
ARG PATCHES
ARG REPOSITORY=https://github.com/eosio/eos.git

COPY patches /patches

RUN git clone -b $SRCTAG --depth 1 $REPOSITORY --recursive \
    && cd eos \
    && echo PATCHING... && for patch in $PATCHES; do echo APPLYING PATCH $patch; patch -p1 < /patches/$patch; done && echo PATCHED \
    && echo "$SRCTAG:$(git rev-parse HEAD)" > /etc/eosio-version \
    && echo $REPOSITORY ref $SRCTAG revision `git describe --always --long` > /etc/eosio-build-version \
    && ./scripts/eosio_build.sh -y -s EOS -p / -P \
    && ./scripts/eosio_install.sh \
    # The `eosio_install` installs by default to a fixed child folder named
    # `eosio`. We want to keep our old convention `/opt/eos`, hence, let's
    # create a symlink to keep both working.
    && ln -s /opt/eosio /opt/eos \
    && cmake --build /tmp/build --target install

ENV EOSIO_ROOT=/opt/eosio
ENV INSTALL_PREFIX /opt/eos
ENV LD_LIBRARY_PATH /usr/local/lib
