ARG EOSIO_BUILDENV_TAG

FROM gcr.io/eoscanada-shared-services/eosio-buildenv:$EOSIO_BUILDENV_TAG as builder

ARG SRCTAG

# Copy the whole context, which was the actual repository to build, into `/git`.
COPY ./ /git/
WORKDIR /git

RUN echo "Building $SRCTAG using $EOSIO_BUILDENV_TAG" \
    && echo "$SRCTAG:$(git rev-parse HEAD)" > /etc/eosio-version \
    && echo `git config --get remote.origin.url` ref $SRCTAG revision `git describe --always --long` > /etc/eosio-build-version \
    && ./scripts/eosio_build.sh -y -s EOS -i "/opt/eosio/" -P \
    && ./scripts/eosio_install.sh
