ARG NODEOS_FULL_TAG

FROM gcr.io/eoscanada-shared-services/eosio-nodeos-full:$NODEOS_FULL_TAG as builder

FROM ubuntu:18.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install openssl less curl vim libpython2.7 && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/lib/* /usr/local/lib/
COPY --from=builder /opt/eos/bin /opt/eosio/bin
COPY --from=builder /eos/Docker/nodeosd.sh /opt/eosio/bin/nodeosd.sh
RUN chmod +x /opt/eosio/bin/nodeosd.sh

VOLUME /opt/eosio/bin/data-dir

ENV PATH /opt/eosio/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
