FROM ubuntu:18.04 as builder

ARG SRCTAG=v1.8.1
ARG REPOSITORY=https://github.com/eosio/eos.git

# In a separate layer to improve potential re-use
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install git cmake clang-7 sudo

RUN git clone -b $SRCTAG --depth 1 $REPOSITORY --recursive \
    && cd eos \
    && echo "$SRCTAG:$(git rev-parse HEAD)" > /etc/buildenv-eosio-version \
    && echo $REPOSITORY ref $SRCTAG revision `git describe --always --long` > /etc/buildenv-eosio-build-version \
    && echo "Preparing build environment..." \
    && echo "Patching eosio-build.sh to only install dependencies..." \

    ##
    # This find a particular place in script just before launching the actual build process and make it stop at this point.
    # This ensures that we only install the actual build dependencies at the right location without actually launching
    # a full build process for nothing.
    #
    # Needs to be re-checked when build environment is re-built to ensure the sed replacement still
    # happens at the right location.
    #
    && sed -i 's/execute cd \$BUILD_DIR/echo "Done"; exit 0/g' ./scripts/eosio_build.sh \

    ##
    # Performing actual installation of dependencies
    #
    && echo "Installing the actual build dependencies..." \
    && ./scripts/eosio_build.sh -y -i "/opt/eosio" -P \

    ##
    # Clean up of unnecessary files
    #
    && echo "Performing clean up of unnecessary files..." \
    && rm -rf /eos \
    # && rm -rf /opt/eosio/src/clang8 /opt/eosio/src/llvm /opt/eosio/src/cmake-3.13.2 \
    # && cd /opt/eosio/src/boost_1_71_0 && rm -rf boost doc libs status more tools \
    && rm -rf /var/lib/apt/lists/*
