FROM ubuntu:18.04 as builder

ARG SRCTAG=v1.8.0-rc1
ARG REPOSITORY=https://github.com/eosio/eos.git

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get -y install git cmake clang-7 sudo \
    && git clone -b $SRCTAG --depth 1 $REPOSITORY --recursive \
    && cd eos \
    && echo "$SRCTAG:$(git rev-parse HEAD)" > /etc/buildenv-eosio-version \
    && echo $REPOSITORY ref $SRCTAG revision `git describe --always --long` > /etc/buildenv-eosio-build-version \
    && echo "Preparing build environment..." \
    && echo "Patching eosio-build.sh to only install dependencies..." \
    # This find a particular place in script just before launching the actual build process and make it stop at this point.
    # This ensures that we only install the actual build dependencies at the right location without actually launching
    # a full build process for nothing.
    #
    # Needs to be re-checked when build environment is re-built to ensure the sed replacement still
    # happens at the right location.
    && sed -i 's/cd \$BUILD_DIR/echo "Done"; exit 0/g' ./scripts/eosio_build.sh \
    && echo "Installing the actual build dependencies..." \
    && ./scripts/eosio_build.sh -y -f -p "" -P \
    && echo "Performing clean up of unnecessary files..." \
    && cd .. && rm -rf eos \
    && rm -rf /var/lib/apt/lists/*

## TODO: Remove all build folder of the dev dependencies (if they are not necessary),
##       most should be deletable leaving only the built libraries for each project.
