FROM ubuntu:18.04

ARG EOSIO_CDT_PACKAGE_NAME
ARG EOSIO_CDT_VERSION

WORKDIR /workspace

LABEL description="Image containing the eosio.cdt development toolchain for EOS Blockchains" \
      version="${EOSIO_CDT_VERSION}" \
      packageName="${EOSIO_CDT_PACKAGE_NAME}"

LABEL maintainer="Alexandre Bourget <alex@eoscanada.com>" \
      maintainer="Francois Proulx <francois@eoscanada.com>" \
      maintainer="Matthieu Vachon <matt@eoscanada.com>"

RUN echo 'APT::Install-Recommends 0;' >> /etc/apt/apt.conf.d/01norecommends \
  && echo 'APT::Install-Suggests 0;' >> /etc/apt/apt.conf.d/01norecommends \
  && apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y make cmake g++ openssl ca-certificates wget \
  && rm -rf /var/lib/apt/lists/*

RUN wget "https://github.com/eosio/eosio.cdt/releases/download/v${EOSIO_CDT_VERSION}/${EOSIO_CDT_PACKAGE_NAME}" \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y ./${EOSIO_CDT_PACKAGE_NAME} \
  && rm -rf ./${EOSIO_CDT_PACKAGE_NAME}
