ARG EOSIO_BUILDENV_TAG

FROM gcr.io/eoscanada-shared-services/eosio-buildenv:$EOSIO_BUILDENV_TAG as builder

ARG SRCTAG
ARG PATCHES
ARG REPOSITORY=https://github.com/eosio/eos.git

COPY patches /patches

RUN git clone -b $SRCTAG --depth 1 $REPOSITORY --recursive \
    && cd eos \
    && echo PATCHING... && for patch in $PATCHES; do echo APPLYING PATCH $patch; patch -p1 < /patches/$patch; done && echo PATCHED \
    && echo "$SRCTAG:$(git rev-parse HEAD)" > /etc/eosio-version \
    && echo $REPOSITORY ref $SRCTAG revision `git describe --always --long` > /etc/eosio-build-version \
    && ./scripts/eosio_build.sh -y -s EOS -i "/" -P \
    && ./scripts/eosio_install.sh
