ARG SRCTAG
ARG BLDTAG

FROM eosio/builder:$BLDTAG as builder

ARG SRCTAG
ARG PATCHES
ARG REPOSITORY=https://github.com/eosio/eos.git

COPY patches /patches

RUN git clone -b $SRCTAG --depth 1 $REPOSITORY --recursive \
    && cd eos \
    && echo PATCHING... && for patch in $PATCHES; do echo APPLYING PATCH $patch; patch -p1 < /patches/$patch; done && echo PATCHED \
    && echo "$SRCTAG:$(git rev-parse HEAD)" > /etc/eosio-version \
    && echo $REPOSITORY ref $SRCTAG revision `git describe --always --long` > /etc/eosio-build-version \
    && echo "Installing missing dependencies..." \
    && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install libusb-1.0-0-dev libcurl4-gnutls-dev \
    && ./scripts/eosio_build.sh -s EOS -p / \
    && mv /opt/eosio /opt/eos
    && cp --remove-destination `readlink /usr/lib/x86_64-linux-gnu/libz.so` /usr/lib/x86_64-linux-gnu/libz.so \
    && cp --remove-destination `readlink /usr/lib/x86_64-linux-gnu/libbz2.so` /usr/lib/x86_64-linux-gnu/libbz2.so \
    && cmake --build /tmp/build --target install

ENV BOOST /usr/local/include
ENV EOSIO_ROOT=/opt/eosio
ENV INSTALL_PREFIX /opt/eos
ENV LD_LIBRARY_PATH /usr/local/lib
ENV PREFIX /opt
